CREATE TABLE `Log` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`MachineName` VARCHAR(50) NOT NULL DEFAULT '',
	`Logged` DATE NULL DEFAULT CURRENT_TIMESTAMP,
	`Level` VARCHAR(50) NOT NULL DEFAULT '',
	`Message` TEXT NOT NULL DEFAULT '0',
	`Logger` VARCHAR(250) NULL DEFAULT '',
	`Callsite` TEXT NULL DEFAULT NULL,
	`Exception` TEXT NULL DEFAULT NULL,
	PRIMARY KEY (`Id`)
)
COMMENT='Tabla de log de errores'
COLLATE='utf8_general_ci'
AUTO_INCREMENT=1
;