// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiMaVeh.DataAccess.Model;

namespace SiMaVeh.DataAccess.Migrations
{
    [DbContext(typeof(SiMaVehContext))]
    [Migration("20200505232400_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SiMaVeh.Domain.Models.Direccion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Calle")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("LocalidadId")
                        .HasColumnType("bigint");

                    b.Property<int>("NumeroCalle")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadId");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.EntidadReparadora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("DireccionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("TipoEntidadReparadoraId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DireccionId");

                    b.HasIndex("TipoEntidadReparadoraId");

                    b.ToTable("EntidadesReparadoras");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.EquipamientoAirbags", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("DelanteroDerecho")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DelanteroIzquierdo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Guantera")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TraseroDerecho")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TraseroIzquierdo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Volante")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("EquipamientosAirbags");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.FuenteEnergia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("MarcaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("TipoFuenteEnergiaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.HasIndex("TipoFuenteEnergiaId");

                    b.ToTable("FuentesEnergia");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.GrupoModelo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("MarcaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("GruposModelo");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Localidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CPA")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("PartidoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Mantenimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Accion")
                        .HasColumnType("int");

                    b.Property<long?>("MonedaMontoRecambioId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MontoRecambio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long?>("RecambioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReparadorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ServicioReparadorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MonedaMontoRecambioId");

                    b.HasIndex("RecambioId");

                    b.HasIndex("ReparadorId");

                    b.HasIndex("ServicioReparadorId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Marca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.ModeloVehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AceiteRecomendadoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AirbagsId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FuenteEnergiaRecomendadaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GrupoModeloId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TipoFuenteEnergiaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Version")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("AceiteRecomendadoId");

                    b.HasIndex("AirbagsId");

                    b.HasIndex("FuenteEnergiaRecomendadaId");

                    b.HasIndex("GrupoModeloId");

                    b.HasIndex("TipoFuenteEnergiaId");

                    b.ToTable("ModelosVehiculo");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Moneda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Monedas");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Neumatico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AnchuraSeccionalNominal")
                        .HasColumnType("int");

                    b.Property<int>("ConstruccionCarcasa")
                        .HasColumnType("int");

                    b.Property<int>("DiametroLLanta")
                        .HasColumnType("int");

                    b.Property<int>("IndiceCarga")
                        .HasColumnType("int");

                    b.Property<string>("IndiceVelocidad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("MarcaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("RelacionAnchoAlto")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Neumaticos");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Pais", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Partido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("ProvinciaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.PeriodicidadMantenimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Anios")
                        .HasColumnType("int");

                    b.Property<int>("Dias")
                        .HasColumnType("int");

                    b.Property<bool>("EsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("Kilometros")
                        .HasColumnType("bigint");

                    b.Property<int>("Meses")
                        .HasColumnType("int");

                    b.Property<long?>("ModeloVehiculoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TargetMantenimientoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ModeloVehiculoId");

                    b.HasIndex("TargetMantenimientoId");

                    b.ToTable("PeriodicidadesMantenimiento");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("TipoDocumentoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.PresionNeumatico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("EsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ModeloVehiculoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NeumaticoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("RuedasDelanteras")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RuedasTraseras")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ModeloVehiculoId");

                    b.HasIndex("NeumaticoId");

                    b.ToTable("PresionesNeumaticos");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Provincia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("PaisId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Recambio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("MarcaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Recambios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Recambio");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Relations.KitRecambio", b =>
                {
                    b.Property<long>("KitId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecambioId")
                        .HasColumnType("bigint");

                    b.HasKey("KitId", "RecambioId");

                    b.HasIndex("RecambioId");

                    b.ToTable("KitRecambio");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Relations.ReparadorEntidadReparadora", b =>
                {
                    b.Property<long>("ReparadorId")
                        .HasColumnType("bigint");

                    b.Property<long>("EntidadReparadoraId")
                        .HasColumnType("bigint");

                    b.HasKey("ReparadorId", "EntidadReparadoraId");

                    b.HasIndex("EntidadReparadoraId");

                    b.ToTable("ReparadorEntidadReparadora");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.ServicioReparador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("EntidadReparadoraId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("KilometrajeVehiculo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long?>("MonedaMontoManoObraId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MontoManoObra")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long?>("VehiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EntidadReparadoraId");

                    b.HasIndex("MonedaMontoManoObraId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("ServiciosReparadores");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.TargetMantenimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("TargetsMantenimiento");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TargetMantenimiento");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Telefono", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<long?>("PersonaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TipoTelefonoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoTelefonoId");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.TipoCambio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("CoeficienteCambio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("MonedaDestinoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MonedaOrigenId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MonedaDestinoId");

                    b.HasIndex("MonedaOrigenId");

                    b.ToTable("TiposCambio");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.TipoDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.TipoEntidadReparadora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("TiposEntidadReparadora");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.TipoFuenteEnergia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("TiposFuenteEnergia");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.TipoTelefono", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("TiposTelefono");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.UbicacionPieza", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("Izquierda")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Superior")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("UbicacionesPieza");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Vehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AnioFabricacion")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Kilometraje")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long?>("ModeloVehiculoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ModeloVehiculoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vehiculos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Vehiculo");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Reparador", b =>
                {
                    b.HasBaseType("SiMaVeh.Domain.Models.Persona");

                    b.HasDiscriminator().HasValue("Reparador");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Usuario", b =>
                {
                    b.HasBaseType("SiMaVeh.Domain.Models.Persona");

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Kit", b =>
                {
                    b.HasBaseType("SiMaVeh.Domain.Models.Recambio");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasDiscriminator().HasValue("Kit");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Repuesto", b =>
                {
                    b.HasBaseType("SiMaVeh.Domain.Models.Recambio");

                    b.Property<string>("CodigoIdentificador")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("ModeloVehiculoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TargetMantenimientoId")
                        .HasColumnType("bigint");

                    b.HasIndex("ModeloVehiculoId");

                    b.HasIndex("TargetMantenimientoId");

                    b.HasDiscriminator().HasValue("Repuesto");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Aceite", b =>
                {
                    b.HasBaseType("SiMaVeh.Domain.Models.TargetMantenimiento");

                    b.Property<int>("ViscosidadSAEAltaTemperatura")
                        .HasColumnType("int");

                    b.Property<int>("ViscosidadSAEBajaTemperatura")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Aceite");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Fluido", b =>
                {
                    b.HasBaseType("SiMaVeh.Domain.Models.TargetMantenimiento");

                    b.HasDiscriminator().HasValue("Fluido");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Pieza", b =>
                {
                    b.HasBaseType("SiMaVeh.Domain.Models.TargetMantenimiento");

                    b.Property<string>("UbicacionPiezaId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasIndex("UbicacionPiezaId");

                    b.HasDiscriminator().HasValue("Pieza");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Automovil", b =>
                {
                    b.HasBaseType("SiMaVeh.Domain.Models.Vehiculo");

                    b.Property<string>("CodigoColorPintura")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NumeroChasis")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Patente")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasDiscriminator().HasValue("Automovil");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Direccion", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.EntidadReparadora", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId");

                    b.HasOne("SiMaVeh.Domain.Models.TipoEntidadReparadora", "TipoEntidadReparadora")
                        .WithMany()
                        .HasForeignKey("TipoEntidadReparadoraId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.FuenteEnergia", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId");

                    b.HasOne("SiMaVeh.Domain.Models.TipoFuenteEnergia", "TipoFuenteEnergia")
                        .WithMany()
                        .HasForeignKey("TipoFuenteEnergiaId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.GrupoModelo", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Localidad", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Partido", "Partido")
                        .WithMany("Localidades")
                        .HasForeignKey("PartidoId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Mantenimiento", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Moneda", "MonedaMontoRecambio")
                        .WithMany()
                        .HasForeignKey("MonedaMontoRecambioId");

                    b.HasOne("SiMaVeh.Domain.Models.Recambio", "Recambio")
                        .WithMany()
                        .HasForeignKey("RecambioId");

                    b.HasOne("SiMaVeh.Domain.Models.Reparador", "Reparador")
                        .WithMany()
                        .HasForeignKey("ReparadorId");

                    b.HasOne("SiMaVeh.Domain.Models.ServicioReparador", "ServicioReparador")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("ServicioReparadorId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.ModeloVehiculo", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Aceite", "AceiteRecomendado")
                        .WithMany()
                        .HasForeignKey("AceiteRecomendadoId");

                    b.HasOne("SiMaVeh.Domain.Models.EquipamientoAirbags", "Airbags")
                        .WithMany()
                        .HasForeignKey("AirbagsId");

                    b.HasOne("SiMaVeh.Domain.Models.FuenteEnergia", "FuenteEnergiaRecomendada")
                        .WithMany()
                        .HasForeignKey("FuenteEnergiaRecomendadaId");

                    b.HasOne("SiMaVeh.Domain.Models.GrupoModelo", "GrupoModelo")
                        .WithMany()
                        .HasForeignKey("GrupoModeloId");

                    b.HasOne("SiMaVeh.Domain.Models.TipoFuenteEnergia", "TipoFuenteEnergia")
                        .WithMany()
                        .HasForeignKey("TipoFuenteEnergiaId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Neumatico", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Partido", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Provincia", "Provincia")
                        .WithMany("Partidos")
                        .HasForeignKey("ProvinciaId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.PeriodicidadMantenimiento", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.ModeloVehiculo", "ModeloVehiculo")
                        .WithMany()
                        .HasForeignKey("ModeloVehiculoId");

                    b.HasOne("SiMaVeh.Domain.Models.Repuesto", "TargetMantenimiento")
                        .WithMany("PeriodicidadesMantenimiento")
                        .HasForeignKey("TargetMantenimientoId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Persona", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.PresionNeumatico", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.ModeloVehiculo", "ModeloVehiculo")
                        .WithMany("PresionesNeumaticosRecomendadas")
                        .HasForeignKey("ModeloVehiculoId");

                    b.HasOne("SiMaVeh.Domain.Models.Neumatico", "Neumatico")
                        .WithMany()
                        .HasForeignKey("NeumaticoId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Provincia", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Pais", "Pais")
                        .WithMany("Provincias")
                        .HasForeignKey("PaisId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Recambio", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Relations.KitRecambio", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Kit", "Kit")
                        .WithMany()
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiMaVeh.Domain.Models.Recambio", "Recambio")
                        .WithMany("KitRecambio")
                        .HasForeignKey("RecambioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Relations.ReparadorEntidadReparadora", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.EntidadReparadora", "EntidadReparadora")
                        .WithMany("ReparadorEntidadReparadora")
                        .HasForeignKey("EntidadReparadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiMaVeh.Domain.Models.Reparador", "Reparador")
                        .WithMany("ReparadorEntidadReparadora")
                        .HasForeignKey("ReparadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.ServicioReparador", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.EntidadReparadora", "EntidadReparadora")
                        .WithMany("ServiciosReparadores")
                        .HasForeignKey("EntidadReparadoraId");

                    b.HasOne("SiMaVeh.Domain.Models.Moneda", "MonedaMontoManoObra")
                        .WithMany()
                        .HasForeignKey("MonedaMontoManoObraId");

                    b.HasOne("SiMaVeh.Domain.Models.Vehiculo", "Vehiculo")
                        .WithMany("ServiciosReparadores")
                        .HasForeignKey("VehiculoId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Telefono", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Persona", "Persona")
                        .WithMany("Telefonos")
                        .HasForeignKey("PersonaId");

                    b.HasOne("SiMaVeh.Domain.Models.TipoTelefono", "TipoTelefono")
                        .WithMany()
                        .HasForeignKey("TipoTelefonoId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.TipoCambio", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.Moneda", "MonedaDestino")
                        .WithMany()
                        .HasForeignKey("MonedaDestinoId");

                    b.HasOne("SiMaVeh.Domain.Models.Moneda", "MonedaOrigen")
                        .WithMany()
                        .HasForeignKey("MonedaOrigenId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Vehiculo", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.ModeloVehiculo", "ModeloVehiculo")
                        .WithMany()
                        .HasForeignKey("ModeloVehiculoId");

                    b.HasOne("SiMaVeh.Domain.Models.Usuario", "Usuario")
                        .WithMany("Vehiculos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Repuesto", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.ModeloVehiculo", null)
                        .WithMany("RepuestosRecomendados")
                        .HasForeignKey("ModeloVehiculoId");

                    b.HasOne("SiMaVeh.Domain.Models.TargetMantenimiento", "TargetMantenimiento")
                        .WithMany()
                        .HasForeignKey("TargetMantenimientoId");
                });

            modelBuilder.Entity("SiMaVeh.Domain.Models.Pieza", b =>
                {
                    b.HasOne("SiMaVeh.Domain.Models.UbicacionPieza", "UbicacionPieza")
                        .WithMany()
                        .HasForeignKey("UbicacionPiezaId");
                });
#pragma warning restore 612, 618
        }
    }
}
